# tall mountains
#defaultView:Map
SELECT ?item ?itemLabel ?coord ?prominence
WHERE
{
  ?item wdt:P31/wdt:P279* wd:Q8502;
        rdfs:label ?itemLabel;
        wdt:P625 ?coord;
        wdt:P2660 ?prominence;

  FILTER (lang(?itemLabel) = "en")
  .

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }

  #BIND (exists{?item wdt:P31 wd:Q3116906} as ?overFifteenhundred)
}
